var list1 = ["LAZY", "STUPID", "INSECURE", "IDIOTIC", "SLIMY", "SMELLY", "POMPOUS", "COMMUNIST", "DICKNOSE", "PIE-EATING", "RACIST", "ELITIST", "WHITETRASH", "DRUG-LOVING", "BUTTERFACE", "TONEDEAF", "UGLY", "CREEPY", "ARTLESS", "BAWDY", "BESLUBBERING", "BOOTLESS", "CHURLISH", "COCKERED", "CLOUTED", "CRAVEN", "CURRISH", "DANKISH", "DISSEMBLING", "DRONING", "ERRANT", "FAWNING", "FOBBING", "FROWARD", "FROTHY", "GLEEKING", "GOATISH", "GORBELLIED", "IMPERTINENT", "INFECTIOUS", "JARRING", "LOGGERHEADED", "LUMPISH", "MAMMERING", "MANGLED", "MEWLING", "PAUNCHY", "PRIBBLING", "PUKING", "PUNY", "QUALLING", "RANK", "REEKY", "ROGUISH", "RUTTISH", "SAUCY", "SPLEENY", "SPONGY", "SURLY", "TOTTERING", "UNMUZZLED", "VAIN", "VENOMED", "VILLAINOUS", "WARPED", "WAYWARD", "WEEDY", "YEASTY"];
var list2 = ["DOUCHE", "ASS", "TURD", "RECTUM", "BUTT", "COCK", "SHIT", "CROTCH", "TURD", "PRICK", "TAINT", "FUCK", "DICK", "BONER", "SHART", "NUT", "SPHINCTER", "BASE-COURT", "BAT-FOWLING", "BEEF-WITTED", "BEETLE-HEADED", "BOIL-BRAINED", "CLAPPER-CLAWED", "CLAY-BRAINED", "COMMON-KISSING", "CROOK-PATED", "DISMAL-DREAMING", "DIZZY-EYED", "DOGHEARTED", "DREAD-BOLTED", "EARTH-VEXING", "ELF-SKINNED", "FAT-KIDNEYED", "FEN-SUCKED", "FLAP-MOUTHED", "FLY-BITTEN", "FOLLY-FALLEN", "FOOL-BORN", "FULL-GORGED", "GUTS-GRIPING", "HALF-FACED", "HASTY-WITTED", "HEDGE-BORN", "HELL-HATED", "IDLE-HEADED", "ILL-BREEDING", "ILL-NURTURED", "KNOTTY-PATED", "MILK-LIVERED", "MOTLEY-MINDED", "ONION-EYED", "PLUME-PLUCKED", "POTTLE-DEEP", "POX-MARKED", "REELING-RIPE", "ROUGH-HEWN", "RUDE-GROWING", "RUMP-FED", "SHARD-BORNE", "SHEEP-BITING", "SPUR-GALLED", "SWAG-BELLIED", "TARDY-GAITED", "TICKLE-BRAINED", "TOAD-SPOTTED", "UNCHIN-SNOUTED", "WEATHER-BITTEN"];
var list3 = ["PILOT", "CANOE", "CAPTAIN", "PIRATE", "HAMMER", "KNOW", "BOX", "JOCKEY", "NAZI", "WAFFLE", "GOBLIN", "BLOSSOM", "BISCUIT", "CLOWN", "SOCKET", "MONSTER", "HOUND", "DRAGON", "BALLOON", "APPLE-JOHN", "BAGGAGE", "BARNACLE", "BLADDER", "BOAR-PIG", "BUGBEAR", "BUM-BAILEY", "CANKER-BLOSSOM", "CLACK-DISH", "CLOTPOL", "COXCOMB", "CODPIECE", "DEATH-TOKEN", "DEWBERRY", "FLAP-DRAGON", "FLAX-WENCH", "FLIRT-GILL", "FOOT-LICKER", "FUSTILARIA", "GIGLET", "GUDGEON", "HAGGARD", "HARPY", "HEDGE-PIG", "HORN-BEAST", "HUGGER-MUGGER", "JOITHEAD", "LEWDSTER", "LOUT", "MAGGOT-PIE", "MALT-WORM", "MAMMET", "MEASLE", "MINNOW", "MISCREANT", "MOLDWARP", "MUMBLE-NEWS", "NUT-HOOK", "PIGEON-EGG", "PIGNUT", "PUTTOCK", "PUMPION", "RATSBANE", "SCUT", "SKAINSMATE", "STRUMPET", "VARLOT", "VASSAL", "WHEY-FACE", "WAGTAIL"];
var output = "A"

function insult() {
	var output = "A"
	var rand1 = Math.floor(Math.random() * (list1.length - 1));
	if (list1[rand1][0] === "A" || list1[rand1][0] === "E" || list1[rand1][0] === "I" || list1[rand1][0] === "O" || list1[rand1][0] === "U") {
		output += "N";
	}
	output += " " + list1[rand1] + ", ";

	var rand2 = Math.floor(Math.random() * (list2.length - 1));
	output += list2[rand2] + " ";

	var rand3 = Math.floor(Math.random() * (list3.length - 1));
	output += list3[rand3];

	return (output);
};

function generate () {
	document.getElementById("list1").innerHTML = insult();
};